# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
admm_bp <- function(A, b, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMM_admm_bp', PACKAGE = 'ADMM', A, b, xinit, reltol, abstol, maxiter, rho, alpha)
}

#' @keywords internal
#' @noRd
admm_lad <- function(A, b, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMM_admm_lad', PACKAGE = 'ADMM', A, b, xinit, reltol, abstol, maxiter, rho, alpha)
}

#' @keywords internal
#' @noRd
admm_lasso <- function(A, b, lambda, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMM_admm_lasso', PACKAGE = 'ADMM', A, b, lambda, xinit, reltol, abstol, maxiter, rho, alpha)
}

#' @keywords internal
#' @noRd
admm_spca <- function(Sigma, reltol, abstol, maxiter, mu, rho) {
    .Call('_ADMM_admm_spca', PACKAGE = 'ADMM', Sigma, reltol, abstol, maxiter, mu, rho)
}

#' @keywords internal
#' @noRd
admm_tv <- function(b, xinit, lambda, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMM_admm_tv', PACKAGE = 'ADMM', b, xinit, lambda, reltol, abstol, maxiter, rho, alpha)
}

